version: Build {build}

skip_non_tags: true

environment:
    matrix:
        - nodejs_version: "12"
          platform: x64

install:
    - ps: Install-Product node $env:nodejs_version $env:platform
    - "node --version"
    - "npm i -g electron-forge"
    - "npm i -g node-pre-gyp"
    - "npm --version"
    - "npm install"
    - "npm run electron-version"
    - ps: $pycamverter_version = [system.String]::Join(".", (git ls-remote --tags git://github.com/white-lab/pycamverter.git | Foreach-object { [System.Version] ($_ -replace '\w+\s+refs/tags/v([\d\.]+)[\^\{\}]*','${1}') } | sort  | Select-Object -last 1))
    - ps: "echo ${pycamverter_version}"
    - ps: Start-FileDownload https://github.com/white-lab/pycamverter/releases/download/v${pycamverter_version}/PyCAMVerter.exe

# test_script:
#     - yarn test

build_script:
    - ps: $env:DEBUG='electron-forge:*'
    - "electron-forge make"
    - "ls -lh out/make/"

artifacts:
    - path: "out/make/CAMV-win32-x64-*.exe"

deploy:
    - provider: GitHub
      description: "Computer Assisted Manual Validation for Mass Spectrometry Proteomics"
      artifact: /CAMV-.*\.exe/
      draft: false
      prerelease: false
      force_update: true
      on:
        appveyor_repo_tag: true
      auth_token:
        secure: Vt90BNYB5BI/GtFTilnFdNNEC8T+/szE6cmO3M3gpMaMRXzE4p+XNdAHyymTxnJN
